on: pull_request_target
name: Label approved pull requests
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: content-services/label-when-approved-action@master

      env:
        REVIEW_LIST: ${{ vars.QE_LIST }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "qe-approved"
 
